language: node_js
node_js:
- '8.4'
notifications:
  on_success: never
  on_failure: always
  slack:
    secure: IadmuEecXBK0Bm+rOlwuLOwJL1pJS+Q83EScUlOaFeSSr1h992QCyoC1xiDBRdp2xRaowopxjc/qB1t2yw5PLg73jVddhIWED7o7n040pO8q+uqLnXxkrGT9qpT0u0N9L/Q9JL3iSeNYPyI5AkyNYFI8XJ1RldRuv61rqmBBzE0UWIJUDLUdfhvFRPzQJEcevfIrDcbMEgIh1JhrsE+DPQCe4exY/1w2pAL5FKZfcjvP1obFesFTmVBEM+Y12jjRxdNS0h/bd7gbofvwGZw+mPyfw4fpqRkg2dMnD6OEv9E5wJoHR7adzAY9Ey8sgqWgdb68f+raejVnhsqG0lOKSZS4/xNflsGQv0Um8Qd7HktTf1k/FOEe/Iz3wSmKZIym2cX5Ue/xxRbf55O6mmaVLbD5kediFRkgSWglU3Rgh24ZwTrJBm0H4nEGaSiGHJUxxOBU90HAXRpMV558fKtFERutpo74WBTQ+d+GsrRYhkVrCQ1ugy3e31cbxQIcDwKmJlXUoJVF3yLYz8/nQAuuwaTr2rOkjPVYGzXlahhr9jpPMeUOUTS4rorow0TDYqx3AxgE3Qb0UrsttzcfvUyi89u4QUyU3cnxbBE+Y3/zoG1WZmDYLXMT3wS0RS/8OoRKsQNaGQfZbGwi+kNdSNhtOW6FXPCO+NLCtgYMwdL4AQo=